variables:
  GIT_SSL_NO_VERIFY: "true"

image: hub.estaleiro.serpro/pipeline/node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - apk add openssh
    - npm install git+ssh://git@git.serpro:ds-gov/ds-gov-html-validate.git
    - npm set strict-ssl false
    - npm config set registry http://nexus.aic.serpro/repository/npm-group/
    - npm config set @serpro:registry http://nexus.aic.serpro/repository/npm-private/
    - npm install
  artifacts:
    paths:
      - node_modules/

validate_html:
  stage: test
  script: npm run validate:html

validate_sass:
  stage: test
  script: npm run validate:sass
