variables:
  GIT_SSL_NO_VERIFY: "true"

image: hub.estaleiro.serpro/pipeline/node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - rm -rf package-lock.json
    - rm -rf node_modules
    - npm install
  artifacts:
    paths:
      - node_modules/

validate_html:
  stage: test
  script: npm run validate:html

validate_sass:
  stage: test
  script: npm run validate:sass
