variables:
  GIT_SSL_NO_VERIFY: "true"

image: hub.estaleiro.serpro/pipeline/node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - apk add openssh
    - export CYPRESS_INSTALL_BINARY=https://cdn.cypress.io/desktop/3.8.3/linux-x64/cypress.zip
    - export NODE_TLS_REJECT_UNAUTHORIZED=0 
    - npm set strict-ssl false
    - npm config set @serpro:registry http://nexus.aic.serpro/repository/npm-private/
    - npm install
    - ls
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - dist/

validate_html:
  stage: test
  script: npm run validate:html

validate_styles:
  stage: test
  script: npm run validate:styles
