

image: node:18-alpine


cache:
  paths:
    - public


stages:
  - Dependências
  - test
  - performance
  - accessibility
  - Qualidade
  - Build
  - Pages
  - Release

cache:
  paths:
    - node_modules/

Instalar dependências:
  stage: Dependências
  artifacts:
    paths:
      - node_modules
    expire_in: 1 hour
  script:
    - apk --no-cache add git
    - npm install



DS:
  stage: Build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - npm run build
  only:
    - main
    - next
    - merge_requests
    - /\d.(\d|x).(\d|x)(-alpha)?$/
    - /alpha$/

pages-x:
  stage: Pages
  artifacts:
    paths:
      - public
    expire_in: 1 week
    expose_as: "Build"
  script:
    - rm -rf public
    - npm run build
    - mv dist public
  only:
    - main


pages:
  stage: Pages
  script:
    - mkdir -p tmp
    - echo $CI_PIPELINE_ID
    - echo "$CI_PIPELINE_ID" > tmp/index.html
    - mkdir -p public
    - mkdir -p public/$CI_PIPELINE_ID/
    - npm run build
    - mv dist public/$CI_PIPELINE_ID/
    - cp tmp/* public/$CI_PIPELINE_ID/ -R
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public
    expire_in: 5 days

  

