variables:
  GIT_SSL_NO_VERIFY: "true"

image: node:12

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    
    - npm install
    - ls
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - dist/

validate_html:
  stage: test
  script: npm run lint:html

validate_styles:
  stage: test
  script: npm run lint:styles

publish_develop:
  stage: test
  script:
    - "curl -X POST -k -F token=$TRIGGER_TOKEN -F ref=develop https://git.serpro/api/v4/projects/8815/trigger/pipeline"
  only:
    - develop
    - build/develop

