include:
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Verify/Browser-Performance.gitlab-ci.yml
  - template: Verify/Accessibility.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

image: node:18-alpine

stages:
  - Dependências
  - test
  - performance
  - accessibility
  - Qualidade
  - Build
  - Pages
  - Release

cache:
  paths:
    - node_modules/

Instalar dependências:
  stage: Dependências
  artifacts:
    paths:
      - node_modules
    expire_in: 1 hour
  script:
    - apk --no-cache add git
    - npm install

license_scanning:
  artifacts:
    paths: [gl-license-management-report.json]
    reports:
      license_scanning: gl-license-management-report.json
    expire_in: 1 week
    expose_as: "Licenses"

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
    expire_in: 1 week
    expose_as: "Code Quality"
  rules:
    - if: $CODE_QUALITY_DISABLED
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

browser_performance:
  variables:
    URL: https://govbr-ds.gitlab.io/dev/wbc/govbr-ds-wbc/
  artifacts:
    paths: ["sitespeed-results/"]
    expire_in: 1 week
    expose_as: "Browser Performance"

CSS:
  stage: Qualidade
  artifacts:
    when: always
    paths:
      - report-stylelint.txt
    expire_in: 1 week
  script:
    - npx stylelint src/**/*.scss  --formatter verbose --output-file report-stylelint.txt

Commits:
  stage: Qualidade
  artifacts:
    when: always
    paths:
      - report-commitlint.txt
    expire_in: 1 week
  before_script:
    - apk --no-cache add git
  script:
    - >
      if [ "${CI_BUILD_BEFORE_SHA}" = "0000000000000000000000000000000000000000" ]; then
        echo "commitlint from HEAD^"
        npx commitlint -x @govbr-ds/commit-config -f HEAD^ > report-commitlint.txt
      else
        echo "commitlint from ${CI_BUILD_BEFORE_SHA}"
        br=`git branch -r --contains ${CI_BUILD_BEFORE_SHA}`
        if [ ! -n $br ]; then
          npx commitlint -x @govbr-ds/commit-config -f HEAD^ > report-commitlint.txt
        else
          npx commitlint -x @govbr-ds/commit-config -f "${CI_BUILD_BEFORE_SHA}" > report-commitlint.txt
        fi
      fi

DS:
  stage: Build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - npm run build
  only:
    - main
    - next
    - merge_requests
    - /\d.(\d|x).(\d|x)(-alpha)?$/
    - /alpha$/

pages:
  stage: Pages
  artifacts:
    paths:
      - public
    expire_in: 1 week
    expose_as: "Build"
  script:
    - rm -rf public
    - npm run build
    - mv dist public
  only:
    - main

pages-branch:
  stage: Pages
  artifacts:
    paths:
      - public
    expire_in: 1 week
    expose_as: "Build"
  script:
    - mkdir -p public/$CI_PIPELINE_ID
    - npm run build
    - cp -R ./dist public/$CI_PIPELINE_ID
  

Semantic Release:
  stage: Release
  when: manual
  environment:
    name: production
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  before_script:
    - apk --no-cache add git zip
  script:
    - npx semantic-release
  only:
    - main
    - next
    - /\d.(\d|x).(\d|x)(-alpha)?$/
    - /alpha$/
