#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: stylish
  # Output file instead of logging results
  output-file: ''
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include:
    - 'assets/styles/**/*.s+(a|c)ss'
    - 'base/**/*.s+(a|c)ss'
    - 'components/**/*.s+(a|c)ss'
    - 'templates/**/*.s+(a|c)ss'
# Rule Configuration
rules:
  attribute-quotes:
    - 2
    - include: true
  bem-depth: 0
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - style: '1tbs'
    - allow-single-line: true
  class-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 2
    - leading-underscore: false
    - filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    - include: false
  empty-line-between-blocks: 0
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  max-file-line-count: 0
  max-line-length: 0
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
  mixins-before-declarations: 2
  nesting-depth: 0
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 2
  no-combinators: 0
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 0
  no-disallowed-property-values: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-media-feature-vendor-prefix: 0
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-property-vendor-prefix: 0
  no-qualifying-elements: 0
  no-selector-vendor-prefix: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-url-domains: 2
  no-url-protocols:
    - 2
    - allow-protocol-relative-urls: false
  no-value-vendor-prefix: 0
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
  property-sort-order:
    - 2
    - order: alphabetical
    - ignore-custom-properties: false
  property-units: 0
  pseudo-element: 2
  shorthand-values: 1
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon:
    - 2
    - include: true
  url-quotes: 2
  variable-for-property: 2
  variable-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
